name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Node.js for Svelte frontend
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # specify the Node.js version

    # Install and build the frontend
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build frontend
      run: npm run build
      working-directory: ./frontend

    # Setup Go for backend
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18' # This has been bottleneck

    - name: Install Go dependencies
      run: go mod tidy
      working-directory: ./backend

    - name: Build backend
      run: go build .
      working-directory: ./backend
